table stg_pbi_dataset_details_2
	isHidden
	lineageTag: c97e2da4-bd34-46fa-b699-25c9d770cf75

	column id
		dataType: string
		isHidden
		lineageTag: 17fe0dcd-589c-4bb2-ab23-d6d5d053c8c5
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dataset name'
		dataType: string
		isHidden
		lineageTag: f56d5399-c71a-497e-a71b-4e650ee73fec
		summarizeBy: none
		sourceColumn: Dataset name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column configuredby
		dataType: string
		isHidden
		lineageTag: 8f18eb4d-953c-4054-a9c7-6fdc7c812052
		summarizeBy: none
		sourceColumn: configuredby

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isrefreshable
		dataType: string
		isHidden
		lineageTag: 8d7d5b0a-2102-441e-8f2d-2b45ac273dac
		summarizeBy: none
		sourceColumn: isrefreshable

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column iseffectiveidentityrequired
		dataType: string
		isHidden
		lineageTag: 3182d54f-3e13-4c54-b85e-debc4987d304
		summarizeBy: none
		sourceColumn: iseffectiveidentityrequired

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column isondedicatedcapacity
		dataType: string
		isHidden
		lineageTag: ea6332fd-5576-4c5c-a5ec-a777e5520229
		summarizeBy: none
		sourceColumn: isondedicatedcapacity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column workspaceid
		dataType: string
		isHidden
		lineageTag: a4deace0-8e27-4ac3-ac6c-1255196ce136
		summarizeBy: none
		sourceColumn: workspaceid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column createddatetime
		dataType: string
		isHidden
		lineageTag: 20627614-0069-4987-8a80-b40d3d8b7618
		summarizeBy: none
		sourceColumn: createddatetime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column modifieddatetime
		dataType: string
		isHidden
		lineageTag: 5a3e92fa-2961-4f6d-a5ca-e365926a37a9
		summarizeBy: none
		sourceColumn: modifieddatetime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column loaded_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d619fbd3-ccb6-428f-a690-cc917d36a139
		summarizeBy: none
		sourceColumn: loaded_date

		variation Variation
			isDefault
			relationship: 92b6ed04-3cfc-444e-b113-a3ae6b21c9c5
			defaultHierarchy: LocalDateTable_03b0e365-6595-4dde-ad5f-7378aca7c989.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition stg_pbi_dataset_details_2 = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=PowerBI_Redshift_DataOps", [HierarchicalNavigation=true]),
				    dataopsdw_Database = Source{[Name="dataopsdw",Kind="Database"]}[Data],
				    stg_powerbi_metadata_Schema = dataopsdw_Database{[Name="stg_powerbi_metadata",Kind="Schema"]}[Data],
				    stg_pbi_dataset_details_Table = stg_powerbi_metadata_Schema{[Name="stg_pbi_dataset_details",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(stg_pbi_dataset_details_Table,{{"name", "Dataset name"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

